### ISSUE TITLE
Stack name error on pulumi up: stack names are limited to 100 characters and may only ...

### ISSUE THREAD

**Issue by LucasJC** [pulumi/pulumi-aws-static-website#13]
### What happened?

Error on executing pulumi up with a stack named 'dev'

### Steps to reproduce

Just execute `pulumi up`

### Expected Behavior

Successful preview

### Actual Behavior

>pulumi up
Please choose a stack, or create a new one: dev
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Previewing update (dev):
     Type                                        Name               Plan       Info
 +   pulumi:pulumi:Stack                         frontend-dev  create     1 error; 14 messages
 +   └─ pulumi-aws-static-website:index:Website  web                create    

Diagnostics:
  pulumi:pulumi:Stack (frontend-dev):
    error: stack names are limited to 100 characters and may only contain alphanumeric, hyphens, underscores, or periods
    Error: Command failed: pulumi --stack='dev' stack
    error: stack names are limited to 100 characters and may only contain alphanumeric, hyphens, underscores, or periods
    : Error: Command failed: pulumi --stack='dev' stack
    error: stack names are limited to 100 characters and may only contain alphanumeric, hyphens, underscores, or periods
        at checkExecSyncError (node:child_process:828:11)
        at Object.execSync (node:child_process:899:15)
        at execSync (pkg/prelude/bootstrap.js:2115:30)
        at Website.getOrganizationName (C:\snapshot\pulumi-resource-aws-static-website\bin\website.js:96:61)
        at new Website (C:\snapshot\pulumi-resource-aws-static-website\bin\website.js:55:46)
        at C:\snapshot\pulumi-resource-aws-static-website\bin\provider.js:48:25
        at Generator.next (<anonymous>)
        at C:\snapshot\pulumi-resource-aws-static-website\bin\provider.js:21:71
        at new Promise (<anonymous>)

    error: Running program 'C:\code\infra\frontend' failed with an unhandled exception:
        at Module.m._compile (C:\code\infra\frontend\node_modules\ts-node\src\index.ts:439:23)        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Object.require.extensions.<computed> [as .ts] (C:\code\infra\frontend\node_modules\ts-node\src\index.ts:442:12)        at Module.load (internal/modules/cjs/loader.js:950:32)

### Output of `pulumi about`

CLI
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME                VERSION
aws                 5.16.0
aws-static-website  0.1.1
docker              3.4.1
nodejs              unknown

Host
OS       Microsoft Windows 11 Home Single Language
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v14.19.3'

### Additional context

My code:
```typescript
import * as aws_static_website from "@pulumi/aws-static-website";
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();
const prefix = config.require("urlPrefix");
const siteURL = `${prefix}mysite.com`;

const web = new aws_static_website.Website("web", {
    sitePath: "./build",
    withCDN: true,
    atomicDeployments: true,
    addWebsiteVersionHeader: true,
    targetDomain: siteURL,
    error404: "index.html"
});

export const websiteURL = web.websiteURL;
export const bucketName = web.bucketName;
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by LucasJC** [comment]
I think there is an issue with the naming for the __pulumiType, in particular with:
```typescript
Website.__pulumiType = 'aws-static-website:index:Website';
```

**Comment by susanev** [comment]
thx for the report! we will take a look as soon as we can! ❤️

**Comment by sean1588** [comment]
We appreciate you reporting this @LucasJC! Thank you :slightly_smiling_face: 

After looking into this a bit, we believe the issue likely has to do with character escaping in windows shells. Can you share a bit more detail on how you are running this? Are you running `pulumi up` in powershell, and also do you happen to be running `pulumi up` from outside of the context of the pulumi project, e.g. `pulumi up --cwd code/infra`. Thanks again and hopefully we will have a fix for you soon.

**Comment by LucasJC** [comment]
> 

Hey, thank you!

I tried both cmd and powershell with the same results. I am executing `pulumi up` as is, from within my project directory

**Comment by sean1588** [comment]
oh wow! thanks for opening that PR! :heart:  
I'll take a look at the PR and test it out!

**Comment by LucasJC** [comment]
Hey @sean1588 !!

Trying the latest update I get the following:
```
Error: failed to register new resource front [aws-static-website:index:Website]: 2 UNKNOWN: pulumi organization not found, set the organization name in your config file to resolve this error by running `pulumi config set pulumiOrganizationName <org name>`
```

I am not currently in any organization so I tried setting a dummy value using the command `pulumi config set pulumiOrganizationName` but now I am getting a different error, this last one may be because I dont really have an org but I dont really know.

```
    error: [runtime] Running program 'C:\code\infra\frontend' failed with an unhandled exception:    
    Error: failed to register new resource front [aws-static-website:index:Website]: Resource monitor is terminating
        at Object.registerResource (C:\code\infra\frontend\node_modules\@pulumi\runtime\resource.ts:292:27)
        at new Resource (C:\code\infra\frontend\node_modules\@pulumi\resource.ts:401:13)
        at new ComponentResource (C:\code\infra\frontend\node_modules\@pulumi\resource.ts:889:9)     
        at new Website (C:\code\infra\frontend\node_modules\@pulumi\website.ts:87:9)
        at Object.<anonymous> (C:\code\infra\frontend\index.ts:8:13)
        at Module._compile (internal/modules/cjs/loader.js:1085:14)
        at Module.m._compile (C:\code\infra\frontend\node_modules\ts-node\src\index.ts:439:23)       
        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Object.require.extensions.<computed> [as .ts] (C:\code\infra\frontend\node_modules\ts-node\src\index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:950:32)
```

Does this mean I cant use this module if I am not part of a pulumi organization?

Thanks!

**Comment by sean1588** [comment]
Hey @LucasJC!

You should be able to just set the `pulumiOrganizationName` to your pulumi username and that should work.
