### ISSUE TITLE
Using certificateARN without targetDomain

### ISSUE THREAD

**Issue by albin-attentec** [pulumi/pulumi-aws-static-website#19]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I sadly have no direct control over my DNS in my current project and I can only request changes manually. This means that I have been able to create an ACM certificate and later can ask for a CNAME to the cloudfront distribution.
However, if I do not assign a targetDomain, the certificate are never assigned to the distribution.

I would like to be able to assign a cert without needing to set up the domain in Route53.

### Affected area/feature

[pulumi-resource-aws-static-website/website.ts](https://github.com/pulumi/pulumi-aws-static-website/blob/bc9ace49b00321b3b5ee9672038781d87a928aa8/provider/cmd/pulumi-resource-aws-static-website/website.ts) lines 305 to 232

**Comment by squaremo** [comment]
Sounds like a reasonable and modest request. I'm sure other people will be in a similar situation -- thanks for speaking up 👍
